const styles = {
  one: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    padding: "10px 20px 0px",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    borderBottomColor: "#A6ACAF",
  },
  two: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    margin: "-25px 38px 10px",
    height: "25px",
    padding: "0px",
    backgroundColor: "black",
    color: "white",
  },
  three: {
    width: "30px",
    height: "25px",
    backgroundColor: "greenyellow",
    paddingTop: "2px",
    marginLeft: "-1px",
  },
  four: {
    justifySelf: "center",
    marginLeft: "auto",
    width: "20px",
    height: "20px",
    backgroundColor: "greenyellow",
    color: "white",
    borderRadius: "30px",
    marginRight: "10px",
  },
  five: {
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
  },
  six: {
    display: "flex",
    flexDirection: "row",
    margin: "0px",
    flexGrow: 0.3,
    justifyContent: "center",
    alignItems: "center",
  },
  seven: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    height: "80px",
  },
  eight: {
    width: "50px",
    height: "50px",
    borderRadius: "50px",
  },
  nine: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "nowrap",
  },
  ten: {
    display: "flex",
    flexDirection: "row",
  },
  eleven: {
    display: "grid",
    textAlign: "center",
    gridTemplateColumns: "1fr 1fr 1fr 2fr 1fr",
    backgroundColor: "#808B96",
  },
  twelve: {
    display: "grid",
    justifyContent: "center",
    alignContent: "center",
    gridTemplateColumns: "1fr 1fr 1fr 2fr 1fr",
  },
  thirt: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  fourt: {
    padding: "5px",
    textAlign: "center",
    borderWidth: "1px",
    borderStyle: "solid",
  },
  fift: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  sixt: {
    padding: "5px",
    textAlign: "center",
    borderWidth: "1px",
    borderStyle: "solid",
  },
  sevent: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  eighti: {
    margin: "18px 38px 10px",
    display: "flex",
    width: "200px",
    height: "25px",
    borderStyle: "solid",
    borderWidth: "1px",
  },
  nineti: {
    borderLeftWidth: "1px",
    borderLeftStyle: "solid",
    paddingLeft: "2px",
  },
};

export default styles;
